# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TelstraiOSAssignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'SnapKit', '~> 4.0.0'
    pod 'SDWebImage', '~> 4.0'
  use_frameworks!




  target 'TelstraiOSAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TelstraiOSAssignmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
